{
    'name': "Villa Nova - Gestion de projet",
    'summary': (
        "Habillage et fonctionnalites facon Asana pour la gestion de projet : "
        "tableaux, Mes taches, Portfolio multi-projets."
    ),
    'version': '18.0.1.0.0',
    'category': 'Services/Project',
    'author': 'Villa Nova',
    'license': 'LGPL-3',
    'depends': ['project', 'hr_timesheet', 'villa_nova_theme', 'base_automation'],
    'data': [
        'security/ir.model.access.csv',
        'security/automation_rules_security.xml',
        'views/project_task_list_view.xml',
        'views/project_task_form_view.xml',
        'views/project_project_form_view.xml',
        'views/my_tasks_action.xml',
        'views/portfolio_action.xml',
        'views/timeline_action.xml',
        'views/workload_action.xml',
        'views/automation_rules_view.xml',
        'views/project_goal_views.xml',
        'views/goals_action.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'villa_nova_project/static/src/scss/board.scss',
            'villa_nova_project/static/src/my_tasks/my_tasks.scss',
            'villa_nova_project/static/src/my_tasks/my_tasks.xml',
            'villa_nova_project/static/src/my_tasks/my_tasks.js',
            'villa_nova_project/static/src/portfolio/portfolio.scss',
            'villa_nova_project/static/src/portfolio/portfolio.xml',
            'villa_nova_project/static/src/portfolio/portfolio.js',
            'villa_nova_project/static/src/timeline/timeline.scss',
            'villa_nova_project/static/src/timeline/timeline.xml',
            'villa_nova_project/static/src/timeline/timeline.js',
            'villa_nova_project/static/src/workload/workload.scss',
            'villa_nova_project/static/src/workload/workload.xml',
            'villa_nova_project/static/src/workload/workload.js',
            'villa_nova_project/static/src/goals/goals.scss',
            'villa_nova_project/static/src/goals/goals.xml',
            'villa_nova_project/static/src/goals/goals.js',
        ],
    },
    'installable': True,
    'application': False,
    'post_init_hook': 'post_init',
}
