{
    'name': "Villa Nova - Processus de Recrutement",
    'summary': "Adapte le pipeline de recrutement Odoo a la procedure RH 2025 de Villa Nova / Infinity Africa Group",
    'version': '18.0.1.0.0',
    'category': 'Human Resources/Recruitment',
    'author': 'Villa Nova',
    'license': 'LGPL-3',
    'depends': [
        'hr_recruitment',
        'website_hr_recruitment',
        'hr_recruitment_survey',
        'base_automation',
        'calendar',
        'hr_recruitment_skills',
    ],
    'data': [
        'security/security.xml',
        'data/recruitment_stage_data.xml',
        'data/survey_prequalification_data.xml',
        'data/mail_templates_data.xml',
        'data/automation_data.xml',
        'views/hr_job_views.xml',
        'views/hr_applicant_views.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': False,
}
