[options]

admin_passwd = REDACTED

db_host = postgres
db_port = 5432
db_user = odoo
db_password = REDACTED

addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons

proxy_mode = True

dbfilter = ^SIRH$
list_db = True